### ISSUE TITLE
market cap

### ISSUE THREAD

**Issue by ashwin31** [upstox/upstox-nodejs#33]
how to get market cap, market cap free float values of a stock?

**Comment by ashwin31** [comment]
@Rahulzz can you help here?

**Comment by Rahulzz** [comment]
@ashwin31 

We do not provide this information as part of our APIs.

For more details, please start a conversation on the [Upstox community](https://community.upstox.com/c/developer-api) where we are actively addressing customer insights, concerns, and feedback.

Thank you!
