### ISSUE TITLE
API Call Error

### ISSUE THREAD

**Issue by medhsv** [upstox/upstox-nodejs#41]
I am trying to test the API Calls using a React App & Express Backend
I am an existing Upstox user, so i have an account.
Created an app for API Keys, as my redirect url i have input a http://localhost:XXXX url

I have tried testing the API calls using Postman, only the Authorize API call as of now which opens a Swagger UI
Next I wanted to try the Get Token, which would not work for me even after enterring my correct Client_ID & Client_Secret (This is the auth step on Swagger UI besides the Server drop down) I also need help with this

Next I finally started with the React App and Express backend, taking refernce code from this very repo
I have made an authorize token button which takes me to Upstox Login page since I am an account holder, and currently logged in
It shows me two methods enter pin and qr scan neither of them are working
Hence hindering my further token generation process

I have also installed the sdk file
Since I have not done this before, I am attaching my server.js (Backend) code below
I have added comments to inform what the particular function does:
const express = require('express');
const bodyParser = require('body-parser');
const cors = require('cors');
const UpstoxClient = require('upstox-js-sdk'); // Ensure this matches the SDK's export
require('dotenv').config();

const app = express();
const PORT = 5000;

app.use(cors());
app.use(bodyParser.json()); // For parsing application/json

// Route to start OAuth flow
app.get('/auth/upstox', (req, res) => {
  const redirectUri = 'https://api-v2.upstox.com/v2/login/authorization/dialog';
  const clientId = process.env.API_KEY; // Ensure this is correct
  const responseType = 'true'; // or 'token'
  const scope = 'false'; // Replace with required scopes

  const authUrl = `${redirectUri}?response_type=${responseType}&client_id=${clientId}&redirect_uri=${encodeURIComponent('http://localhost:3000/callback')}&scope=${scope}`;
  res.redirect(authUrl);
});

// Route to handle OAuth callback and exchange code for token
app.post('/auth/upstox/token', async (req, res) => {
  const { code } = req.body; // Get the authorization code from the request body

  if (!code) {
    return res.status(400).json({ error: 'Authorization code is required' });
  }

  try {
    const apiVersion = 'v2'; // Set the API version if needed
    const clientId = process.env.API_KEY;
    const clientSecret = process.env.API_SECRET; // Replace with your client secret
    const redirectUri = 'http://localhost:3000/callback';
    const grantType = 'authorization_code';

    const opts = {
      code,
      clientId,
      clientSecret,
      redirectUri,
      grantType,
    };

    // Create an instance of the LoginApi
    const loginApi = new UpstoxClient.LoginApi(); 

    // Call the token method
    loginApi.token(apiVersion, opts, (error, data, response) => {
      if (error) {
        console.error('Error fetching token:', {
          message: error.message,
          details: error.response ? error.response.body : 'No response details',
        });
        res.status(500).json({
          error: 'Error exchanging code for token',
          details: error.response ? error.response.body : 'No response details',
        });
      } else {
        res.json(data);
      }
    });
  } catch (error) {
    console.error('Server error:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

// New Route to fetch order details
app.get('/order/details', async (req, res) => {
  const { orderId, tag } = req.query; // Get the orderId and tag from the query params
  const accessToken = req.headers.authorization.split(' ')[1]; // Extract the access token from the Authorization header

  if (!accessToken) {
    return res.status(401).json({ error: 'Access token is required' });
  }

  try {
    const apiVersion = 'v2'; // Set the API version if needed

    // Configure OAuth2 access token for authorization
    let defaultClient = UpstoxClient.ApiClient.instance;
    let OAUTH2 = defaultClient.authentications['OAUTH2'];
    OAUTH2.accessToken = accessToken;

    // Create an instance of the OrderApi
    let apiInstance = new UpstoxClient.OrderApi();
    
    let opts = {}; // Define options for the API call
    if (orderId) opts.orderId = orderId;
    if (tag) opts.tag = tag;

    // Call the getOrderDetails method
    apiInstance.getOrderDetails(apiVersion, opts, (error, data, response) => {
      if (error) {
        console.error('Error fetching order details:', error);
        res.status(500).json({
          error: 'Error fetching order details',
          details: error.response ? error.response.body : 'No response details',
        });
      } else {
        res.json(data);
      }
    });
  } catch (error) {
    console.error('Server error:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

app.listen(PORT, () => console.log(`Server running on http://localhost:${PORT}`));

**Comment by Rahulzz** [comment]
@medhsv 

Are you still experiencing this issue? 

If yes, please raise a query on the [Upstox community](https://community.upstox.com/c/developer-api). This is where both our team and the active developer community are diligently checking and responding.

Thanks!
