### ISSUE TITLE
Typescript not supported in nodejs sdk

### ISSUE THREAD

**Issue by sparshj94** [upstox/upstox-nodejs#43]
@Rahulzz 
Could not find a declaration file for module 'upstox-js-sdk'. 'E:/low_level/node_modules/upstox-js-sdk/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/upstox-js-sdk` if it exists or add a new declaration (.d.ts) file containing `declare module 'upstox-js-sdk';`

**Comment by Rahulzz** [comment]
@sparshj94 We'd be happy to help you with this issue! Please start a conversation on the [Upstox community](https://community.upstox.com/c/developer-api) where like-minded developers and the Upstox team are constantly available to assist you.
