### ISSUE TITLE
historical candle data is time frame of 1 and 30 minute only please provide between 1 to 30 min like 5min, 15min etc 

### ISSUE THREAD

**Issue by sparshj94** [upstox/upstox-nodejs#44]

**Comment by Rahulzz** [comment]
Hello @sparshj94,

This item is in our backlog, but we currently do not have an estimated time for its completion.

For quick updates and continuous engagement, please join the [Upstox community](https://community.upstox.com/c/developer-api) where we are actively addressing customer insights, concerns, and feedback.

Thank you!
